== Updating your DwC Event dataset with the Humboldt extension

****

[discrete]
===== Where does a term belong?
Event datasets can be published with DwC Event terms (any term preceded by ‘dwc’, e.g., term:dwc[dwc:eventID]) and Humboldt extension terms (any term preceded by  ‘eco’, e.g., term:eco[eco:protocolNames]) in the same ‘Event’ table. 

*Populating terms*

Each term in this document is linked with its respective term IRI alias (ex., term:eco[eco:protocolNames]). When populating a term in the ‘Event’ table, ensure that the term is populated at the appropriate/relevent event level(s). Refer to https://eco.tdwg.org/hierarchy/[Properties of hierarchical events in the Humboldt Extension for Ecological Inventories^] for guidance in populating Humboldt extension terms across event levels (e.g., from parent event to child event).

Remember to refer to the definition, comments, and examples provided in the linked documentation to ensure that you are following recommended usage guidelines.

****
