=== Survey date and time 

Complete and accurate reporting of the temporal scope of a survey is crucial to asserting Event structure and providing key contextual information about sampling conditions.

Each Event should include a date or date range in term:dwc[dwc:eventDate]. *Nested datasets* should, at the parent Event level, report a date range encompassing the dates of all relevant child Events.

The time and duration of each Event should be reported using term:dwc[dwc:eventTime] and the paired terms term:eco[eco:eventDurationValue] and term:eco[eco:eventDurationUnit] respectively.

Refer to GBIF’s technical documentation on https://techdocs.gbif.org/en/data-processing/temporal-interpretation[date and time interpretation^] for more guidance on reporting Event dates and times.

[caption=""]
.Event date and temporal scope terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Required
|term:dwc[dwc:eventDate]
|`2018-08-29`

.3+|Recommended
|term:dwc[dwc:eventTime]
|`08:00Z`

|term:eco[eco:eventDurationValue]
|`1`

|term:eco[eco:eventDurationUnit]
|`hour`
|===

<<<
