=== Survey date and time 

Complete and accurate reporting of the temporal scope of a survey is crucial to asserting event structure and providing key contextual information about sampling conditions.

Each Event should report date or date range in term:dwc[dwc:eventDate] regardless of its hierarchical level. *Nested datasets* should, at the parent Event level, report a date range encompassing all survey dates.

The time and duration of each Event should be reported using term:dwc[dwc:eventTime] and the paired terms term:eco[eco:eventDurationValue] and term:eco[eco:eventDurationUnit].

Refer to GBIF’s technical documentation on https://techdocs.gbif.org/en/data-processing/temporal-interpretation[Date and time interpretation^] for more guidance on reporting event dates and
times.

[caption=""]
.Event date and temporal scope terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Required
|term:dwc[dwc:eventDate]
|`2018-08-29`

.3+|Recommended
|term:dwc[dwc:eventTime]
|`08:00Z`

|term:eco[eco:eventDurationValue]
|`1`

|term:eco[eco:eventDurationUnit]
|`hour`
|===
