=== Survey date and time 

===== Why are survey date and time terms important?

Complete and accurate reporting of the temporal scope of a survey is crucial to asserting event structure and providing key contextual information about sampling conditions.

===== Event date and time terms

* *Event date*: Each event should have a reported date or date range in term:dwc[eventDate] regardless of its hierarchical level. Nested datasets should, at the parent event level, report a date range encompassing all survey dates. 
* *Event time and duration*: If reported, note the time and duration of each event using term:dwc[eventTime] and the paired terms term:eco[eventDurationValue] and term:eco[eventDurationUnit]. 

Refer to https://techdocs.gbif.org/en/[GBIF’s technical documentation^] on https://techdocs.gbif.org/en/data-processing/temporal-interpretation[Date and time interpretation^] for more guidance on reporting event dates and times.

[[table-04]]
.Event date and temporal scope terms, their recommended usage (status), and example data entries.

|===
|Status |Term |Example entry

|Required
|term:dwc[eventDate]
|`2018-08-29`, `2007-03-01/2008-05-11`

.3+|Recommended
|term:dwc[eventTime]
|`08:00Z`

|term:eco[eventDurationValue]
|`1`

|term:eco[eventDurationUnit]
|`hour`

|===
