=== Sampling event protocol

A *sampling protocol* provides the details of how the sampling was conducted. Clear communication of the sampling protocol implemented is essential to ensuring the reliability, reproducibility, and reusability of a dataset as detailed knowledge of survey methods facilitates data integration and subsequent analysis. 

[IMPORTANT]
====
Sampling protocol terms should be populated at every event level possible as inheritance in either direction should not be assumed or inferred between event levels.
====

==== Event type

Biological survey event data can result from a wide variety of effort types (e.g., Bioblitzes, inventories). The nature of the survey event should be reported using term:dwc[dwc:eventType]. 

term:dwc[dwc:eventType] should provide a high level overview of sampling effort type but should not be so specific as to overlap with sampling protocol. There is no single, standardized vocabulary for term:dwc[dwc:eventType]. If your organization or community has a controlled vocabulary, it is recommended to apply terms from that. Otherwise, you can refer to the common event types below for guidance.

****
[discrete]
===== Common event types 

* *Project*: Projects are structured initiatives
with an explicitly stated objective or suite of objectives and with clear
targets, timelines, and deliverables. Projects typically are linked to non-biological information identifying participating
organizations and people (agents), funding agencies, and other
high-level administrative information. Biological sampling may only be
one facet of a project’s scope. `Project` as an
term:dwc[dwc:eventType] is typically
most appropriate only at the highest Event level in a nested
dataset.
* *Expedition*: An expedition is an organized information gathering
venture that inherently includes multiple sampling Events and event
types. Expeditions may include multiple taxonomic and/organismal scopes,
any number of documented sampling protocols, and varying degrees of
complexity in survey design. `Expedition` as an
term:dwc[dwc:eventType] is typically
most appropriate at higher Event levels in nested hierarchies.
* *Survey*: A survey is a systematic effort to collect information about the
biological organisms in a specific area at a given time. Surveys
typically included at least one documented protocol and may or may not
have an explicitly defined taxonomic and/or organismal scope. `Survey`
is the most general Event type term and can be applied as an
term:dwc[dwc:eventType] at any event
level.
* *Inventory*: An inventory is a comprehensive survey of the taxa
present in a specific area over an explicit period of time. Inventories
typically have an explicit taxonomic and/or organismal scope and a
well-defined protocol. `Inventory` is typically most appropriate as an
term:dwc[dwc:eventType] at lower Event levels in nested hierarchies.
* *Bioblitz*: A bioblitz is a survey
Event aimed at finding and identifying as many species as possible in a
specific area over a (typically) short, contiguous period of time.
Bioblitzes often include participants (agents) with a wide range of
backgrounds and levels of expertise in biodiversity sciences including
formal biologists as well as the broader, general public. `Bioblitz` as
an term:dwc[dwc:eventType] is typically
most appropriate at lower Event levels in nested hierarchies.
* *Site visit*: A site visit is a single survey, inventory, or sampling at a pre-established geographic location at a discrete time. `Site visit` as an term:dwc[dwc:eventType] is typically most appropriate at the lowest event level in a nested hierarchy.
****

*Inventory event types*

* If term:dwc[dwc:eventType] = `inventory`, the type(s) of search implemented (e.g., restricted search, open search, opportunistic search, trap or sample, compilation) must be reported in term:eco[eco:inventoryTypes]. +
* If _eco:inventoryTypes_ = `compilation`, the compilation type should be reported using term:eco[eco:compilationTypes] and data sources listed in term:eco[eco:compilationSourceTypes].
** A compilation is a summary inventory resulting from the combination of multiple existing inventories (as described in <<Guralnick2018>>). Compilations are aggregates of multiple studies, and may combine surveys employing different protocols, processes, and observers, often with variable reporting of the methods employed or other compiled data sources and literature searches.

[caption=""]
.Event type terms, their recommended usage (status), and example data entries
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Recommended |term:dwc[dwc:eventType]
|`Inventory`

.3+|Recommended if applicable
|term:eco[eco:inventoryTypes]
|`Open search`

|term:eco[eco:compilationTypes]
|`compilationOfExistingSourcesAndSamplingEvents`

|term:eco[eco:compilationSourceTypes]
|`museumSpecimens \| literature`
|===

==== Sampling protocol

term:dwc[samplingProtocol] is required to publish an event dataset to GBIF, however the Humboldt extension includes three (3) terms to capture information about sampling protocol in a more structured manner: 

* term:eco[eco:protocolNames]
* term:eco[eco:protocolDescriptions]
* term:eco[eco:protocolReferences]

****

[NOTE]
.*Updated recommended best practice*
====
* Report the name(s) of the sampling protocol with term:eco[eco:protocolNames]. +
* Capture details of the methods or protocols implemented using term:eco[eco:protocolDescriptions]. + 
* Provide citation information for the protocol via term:eco[eco:protocolReferences]. +
* Retain term:dwc[dwc:samplingProtocol] as a verbatim field of term:eco[eco:protocolNames].
====

[caption=""]
.Survey event protocol terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
|Required
|term:dwc[dwc:samplingProtocol]
|`Visual survey`

.3+|Recommended
|term:eco[eco:protocolNames]
|`Visual survey`

|term:eco[eco:protocolDescriptions]
|`For each site a total list of lichen species (lichenized fungi) was produced based on a careful examination of soil, wood, stone surfaces and bark of trees up to 2 m at three time periods: October-November 2014, February-December 2015 and March and May 2016. Specimens that were not possible to identify with certainty in the field were sampled and subsequently identified in the laboratory. For each species the substrate, e.g. phorophyte (host) species was recorded. All records were registered in www.svampeatlas.dk, and the nomenclature used is in accordance with this database.`

|term:eco[eco:protocolReferences]
|`See Appendix B of Brunbjerg, A.K., Bruun, H.H., Brøndum, L. et al. A systematic survey of regional multi-taxon biodiversity: evaluating strategies and coverage. BMC Ecol 19, 43 (2019). https://doi.org/10.1186/s12898-019-0260-x \| https://doi.org/10.17504/protocols.io.kxygx3jwkg8j/v1`
|===


==== Absence

Organismal *absences* are defined here as the lack of detection of organisms that are members of an explicitly stated as part of the target taxonomic scope. Absence information is critical to understanding species' biogeography, modeling species´ responses to climate- and human-induced environmental change, and conservation planning and resource management. 

* If the dataset includes absence information for one or more occurrences (to be reported in the ´occurrence´ table as term:dwc[dwc:occurrenceStatus] = `absent`), then term:eco[eco:isAbsenceReported] = `true`. +
* A list of absent taxa can be provided using term:eco[eco:absentTaxa] at all relevant levels. Absences should only be reported for taxa within the stated taxonomic and/or organismal scope of a survey. Absence cannot be asserted for bycatch.

==== Abundance

*Abundance* is the number of individuals of the same taxonomic designation in a particular area at a specific time. Abundance data are a key indicator of ecological health. They are necessary for evaluating ecological health, managing invasive species, and informing effective habitat and ecosystem management.

* If the dataset includes any abundance information, term:eco[eco:isAbundanceReported] = ´true´ for all appropriate Event levels. If there is an abundance cap, then term:eco[eco:isAbundanceCapReported]
= ´true´ and the value of the cap should be reported in term:eco[eco:abundanceCap]. +
* If there is no abundance cap, then term:eco[eco:isAbundanceCapReported] = `false`.

[caption=""]
.Absence and abundance terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.3+|Recommended
|term:eco[eco:isAbsenceReported]
|`true` or `false`


|term:eco[eco:isAbundanceReported]
|`true` or `false`


|term:eco[eco:isAbundanceCapReported]
|`true` or `false`

.2+|Share if available
|term:eco[eco:absentTaxa] |

|term:eco[eco:abundanceCap] |`5`
|===

==== Material samples

A *material sample* (term:dwc[dwc:MaterialSample]) is a physical entity ´... that represents an entity of interest in whole or in part.´ Essentially, material samples are specimens collected during a survey Event. They may consist of an entire organism, part of an organism, or a genetic sample.

If the dataset includes at least one specimen from which a material sample was taken:

* term:eco[eco:hasMaterialSamples] = `true` at the appropriate child Event level and at any relevant parent event level, and +
* the type(s) of materials collected should be listed under term:eco[eco:materialSampleTypes] for each relevant Event level.

If the dataset or sampling Event does _not_ include material samples:

* term:eco[eco:hasMaterialSamples] = `false` at all appropriate sampling Event levels.

==== Vouchers

A *voucher* is a physical specimen or material sample collected and accessioned into a museum collection in support of a specific project or survey.

If the dataset has vouchers:

* term:eco[eco:hasVouchers] = ´true´ at the appropriate child Event level and at any relevant parent Event level, and +
* a list of institutions housing them should be shared in term:eco[eco:voucherInstitutions] for each relevant Event level.

If the dataset or sampling event does _not_ include vouchers:

* term:eco[eco:hasVouchers] = `false` at all appropriate sampling Event levels.

==== Least specific target category quantity inclusive

The term term:eco[eco:isLeastSpecificTargetCategoryQuantityInclusive] provides a means by which to indicate to data users if an organismal occurrence record for an specific event reporting an explicit quantity of that organism via the paired terms term:dwc[dwc:organismQuantity] and term:dwc[dwc:organismQuantityType] represents the total number of that organism observed during the Event. That is, it answers the question: _is this the only record of that organism during the event?_

* If the quantity reported using these paired terms includes all the organisms of the same taxon sampled/observed in that single occurrence record, then term:eco[eco:isLeastSpecificTargetCategoryQuantityInclusive] = `true`. +
* If the quantity reported using these paired terms does not include all organisms of the same taxon sampled/observed in that single occurrence record (e.g., there are 2 or more occurrence records reported for the same event), then term:eco[eco:isLeastSpecificTargetCategoryQuantityInclusive] = `false`.

See https://eco.tdwg.org/inclusive/[Guidelines for eco:isLeastSpecificTargetCategoryQuantityInclusive] <<tdwg2024a>> for more information.

==== Data generalizations & information withheld

Although the general recommendation is to share all biodiversity data available at its highest spatio-temporal resolution, situations exist where it is necessary to generalize data prior to sharing a dataset publicly or even withhold information completely. Refer to https://doi.org/10.15468/doc-5jp4-5g10[_Current Best Practices for Generalizing Sensitive Species Occurrence Data_] for guidance on when and how to generalize or withhold information.

===== Reporting data generalizations

If specific aspects of data within the dataset are generalized, a clear summary of the data generalization process should be reported at the appropriate event level using term:dwc[dwc:dataGeneralizations].

For example, if the spatial resolution of locality data for an event is reduced to the nearest half degree, then term:dwc[dwc:dataGeneralizations] = `Coordinates generalized from original GPS coordinates to the nearest half degree grid cell`  for each event to which this treatment was applied. If the location information was generalized for every sampling event site in a nested hierarchy, then at the parent Event level term:dwc[dwc:dataGeneralizations] = `Coordinates for each event site generalized from original GPS coordinates to the nearest half degree grid cell`.

===== Reporting information withheld

If specific data are not reported with the published dataset, a clarifying statement should be provided at the appropriate event level(s) using the term:dwc[dwc:informationWithheld].

For example, if sensitive species data are purposefully excluded from the published data, term:dwc[dwc:informationWithheld] should include a statement along the lines of ´Sensitive species occurrence information not reported´.

==== Verbatim fields

Two verbatim fields are available to provide additional information about an Event. 

* *Field notes:*  Field notes can be copied, transcribed verbatim, or linked into term:dwc[dwc:fieldNotes]. +
* *Event remarks*: Additional comments about a particular Event that don´t fit in any other term can be shared using term:dwc[dwc:eventRemarks].

Both fields can be implemented at any Event at any level.

[caption=""]
.Other survey protocol information and verbatim protocol terms, their recommended usage (status), and example data entries.
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Status |Term |Example entry
.3+|Recommended
|term:eco[eco:hasMaterialSamples]
|`true` or `false`

|term:eco[eco:hasVouchers]
|`true` or `false`

|term:eco[eco:isLeastSpecificTargetCategoryQuantityInclusive]
|`true` or `false`

.5+|Share if available
|term:eco[eco:materialSampleTypes]
|`wholeOrganism`, `blood`

|term:eco[eco:voucherInstitutions]
|`AMNH \| KUNHM`

|term:dwc[dwc:dataGeneralizations]
|`Coordinates generalized from original GPS coordinates to the nearest half degree grid cell`, `Coordinates for each event site generalized from original GPS coordinates to the nearest half degree grid cell`

|term:dwc[dwc:informationWithheld]
|`Sensitive species occurrence information not reported`

|term:dwc[dwc:fieldNotes]
|`Notes available in the Grinnell-Miller Library`

|term:dwc[dwc:eventRemarks]
|
|===
