=== Sampling event protocol

===== What is sampling protocol?

A *Sampling protocol* provides the details of how the sampling was conducted. Clear communication of the sampling protocol implemented is essential to ensuring the reliability, reproducibility, and reusability of a dataset as detailed knowledge of survey methods facilitates data integration and subsequent analysis. 

IMPORTANT: Sampling protocol terms should be populated at every event level possible as inheritance in either direction should not be assumed or inferred between event levels. 

==== Event type

The nature of each sampling event (e.g., survey, inventory, bioblitz) should be reported using term:dwc[eventType].

If term:dwc[eventType] = `inventory`, the type of search implemented (e.g., restricted search, open search, opportunistic search, trap or sample, compilation) must be reported in term:eco[inventoryTypes].

If term:eco[inventoryTypes] = `compilation`, the compilation type should be reported using term:eco[compilationTypes] and data sources captured using term:eco[compilationSourceTypes].

[[table-05]]
.Event type terms, their recommended usage (status), and example data entries
|===
|Status |Term |Example entry
|Recommended
|term:dwc[eventType]
|`Inventory`, `survey`, `Bioblitz`

.3+|Recommended if applicable
|term:eco[inventoryTypes]
|`Open search`, `compilation`

|term:eco[compilationTypes]
|`compilationOfExistingSourcesAndSamplingEvents`

|term:eco[compilationSourceTypes]
|`museumSpecimens`, `literature`

|===

==== Sampling protocol

term:dwc[samplingProtocol] is required to publish an event dataset to GBIF, however the Humboldt extension includes three (3) terms to capture information about sampling protocol in a more structured manner: 

* term:eco[protocolNames]
* term:eco[protocolDescriptions]
* term:eco[protocolReferences]

****
[discrete]
===== Updated recommended best practice 

* Report the name of the sampling protocol with term:eco[protocolNames].
* Capture details of the methods or protocols implemented using term:eco[protocolDescriptions].
* Provide citation information for the protocol via term:eco[protocolReferences].
* Retain term:dwc[samplingProtocol] as a verbatim field of term:eco[protocolNames].
****

[[table-06]]
.Survey event protocol terms, their recommended usage (status), and example data entries
[cols="10,10,80"]
|====
|Status |Term |Example entry
|Required
|term:dwc[samplingProtocol]
|‘Visual survey’

.3+|Recommended
|term:eco[protocolNames]
|`Visual survey`

|term:eco[protocolDescriptions]
|`For each site, a total list of lichen species (lichenized fungi) was produced based on a careful examination of soil, wood, stone surfaces and bark of trees up to 2 m at three time periods: October-November 2014, February-December 2015 and March and May 2016. Specimens that were not possible to identify with certainty in the field were sampled and subsequently identified in the laboratory. For each species, the substrate, e.g. phorophyte (host) species was recorded. All records were registered in www.svampeatlas.dk, and the nomenclature used is in accordance with this database.`

|term:eco[protocolReferences]
|`See Appendix B of Brunbjerg AK, Bruun HH, Brøndum L et al. (2019) A systematic survey of regional multi-taxon biodiversity: evaluating strategies and coverage. BMC Ecol 19: 43. https://doi.org/10.1186/s12898-019-0260-x`, +
`https://www.google.com/url?q=https://www.protocols.io/view/nanopore-minion-kxygx3jwkg8j/v1&sa=D&source=docs&ust=1736780486391914&usg=AOvVaw3oB8oSZiV-MKw0Qf1xFZe0`
|===

==== Material samples

*What are material samples?*

A http://rs.tdwg.org/dwc/terms/MaterialSample[material sample^] is an entity "...that represents an entity of interest in whole or in part." Essentially, material samples are specimens collected during the survey event. They may consist of an entire organism, part of an organism, or a genetic sample.

*Reporting material samples*

If the dataset includes at least one material sample:

* term:eco[hasMaterialSamples] = ‘TRUE’ at the appropriate child event level and at any relevant parent event level, and
* the type(s) of materials collected should be listed under term:eco[materialSampleTypes] for each relevant event level

If the dataset or sampling event does not include material samples:

* term:eco[hasMaterialSamples] = ‘FALSE’ at all appropriate sampling event levels.

==== Vouchers

*What are vouchers?*

A voucher is a specimen or material sample collected and accessioned into a museum collection in support of a specific project or survey effort. 

*Reporting vouchers*

If the dataset has vouchers:

* term:eco[hasVouchers] = ‘TRUE’ at the appropriate child event level and at any relevant parent event level, and
* a list of institutions housing them should be shared in term:eco[voucherInstitutions] for each relevant event level. 

If the dataset or sampling event does not include vouchers: 

* term:eco[hasVouchers] = ‘FALSE’ at all appropriate sampling event levels

Least specific target category quantity inclusive

The term term:eco[isLeastSpecificTargetCategoryQuantityInclusive] provides a means by which to indicate to data users if an organismal occurrence record for a specific event reporting an explicit quantity of that organism via the paired terms term:dwc[organismQuantity] and term:dwc[organismQuantityType] represents the total number of that organism observed during the event. That is, it answers the question: is this the only record of that organism during the event?

* If the quantity reported using these paired terms includes all the organisms of the same taxon sampled/observed in that single occurrence record, then term:eco[isLeastSpecificTargetCategoryQuantityInclusive] = ‘TRUE’ 
* If the quantity reported using these paired terms does not include all organisms of the same taxon sampled/observed in that single occurrence record (e.g. there are two or more occurrence records reported for the same event), then term:eco[isLeastSpecificTargetCategoryQuantityInclusive] = ‘FALSE.’

Refer to Guidelines for term:eco[isLeastSpecificTargetCategoryQuantityInclusive] for more information.

==== Verbatim fields

Two verbatim fields are available to provide additional information about an event. 
Field notes can be copied, transcribed verbatim, or linked into dwc:fieldNotes. 
Additional comments about a particular Event that don’t fit in any other term can be shared using dwc:eventRemarks. 
Both fields can be applied to any event at any level.

Other survey protocol information and verbatim protocol terms, their recommended usage (status), and example data entries.
Status
Term
Example entry
Recommended
eco:hasMaterialSamples
‘TRUE’ or ‘FALSE’
eco:hasVouchers
‘TRUE’ or ‘FALSE’
eco:isLeastSpecificTargetCategoryQuantityInclusive
‘TRUE’ or ‘FALSE’
Share if available
eco:materialSampleTypes
‘wholeOrganism’ | ‘blood’
eco:voucherInstitutions
‘AMNH’ | ‘KUNHM’
dwc:fieldNotes
‘Notes available in the Grinnell-Miller Library’
dwc:eventRemarks




