=== Scope and completeness

*What are survey scope and survey completeness?*

Scope relates to the biodiversity targeted (or not targeted) during a survey. Completeness indicates the thoroughness of a survey relative to the stated scope. Structured reporting of explicitly stated survey scopes and completeness is necessary for evaluating and reporting completeness and is critical to understanding if the data can be used to assert absences (non-detections) of taxa.

Scope terms can be applied at any event level and recommended best practice is to report only the information that is explicitly available.

==== Verbatim scope

The full verbatim scope explicitly identifying the full suite of stated parameters defining the breadth of a sampling event should be reported using term:eco[verbatimTargetScope]. term:eco[verbatimTargetScope] is particularly useful for capturing scope conditions not covered by existing taxonomic or organismal scope terms.

[[table-08]]
.General scope terms, their recommended usage (status), and example data entries.
|===
|Status |Term |Example entry
|Recommended
|term:eco[verbatimTargetScope]
|`Adult flying insects`
|===

==== Taxonomic scope

*Why is taxonomic scope important?*

Providing taxonomic scope enables reliable, quantitative, including statistical interpretation of survey and monitoring data. It is essential to interpret local non-detection as local absences.

*Taxonomic scope terms*

An explicitly stated targeted or intentionally excluded taxonomic scope should be reported using term:eco[targetTaxonomicScope] and term:eco[excludedTaxonomicScope].

* If a specific person or persons is recorded as making the taxonomic identifications relevant to the stated survey scope(s), they should be acknowledged via term:dwc[identifiedBy]. Best practice is to use a unique identifier (e.g. ORCiD), if available.
* If every organism included in term:eco[targetTaxonomicScope] that was observed during an event was reported, then term:eco[isTaxonomicScopeFullyReported] = `TRUE`; if not, term:eco[isTaxonomicScopeFullyReported] = `FALSE`.

If taxonomic completeness is known, term:eco[taxonCompletenessReported] should be populated as either `reportedComplete` or `reportedIncomplete` and the method used to assess completeness reported in term:eco[taxonCompletenessProtocols]. If taxonomic completeness is not reported, term:eco[:taxonCompletenessReported] = `notReported`.

[[table-09]]
.Taxonomic scope terms, their recommended usage (status), and example data entries.
|===
|Status |Term |Example entry
.2+|Recommended
|term:eco[targetTaxonomicScope}
|`Arthropods`

|term:eco[excludedTaxonomicScope]
|`Aves`, `Mammalia`
|===

.4+|Share if available
|term:dwc[identifiedBy]
|`https://orcid.org/0000-0002-9216-2917`, `https://orcid.org/0000-0002-0786-4069`

|term:eco[isTaxonomicScopeFullyReported]
|`TRUE` or `FALSE`

|term:eco[taxonCompletenessReported]
|`reportedComplete`, `reportedIncomplete`, or `notReported` 

|term:eco[taxonCompletenessProtocols]
|`Based on sampling effort`

==== Organismal scope
Why are organismal scope terms important?
As with taxonomic scope, providing organismal scope information when relevant enables reliable, quantitative interpretation of survey and monitoring data and can be essential to interpreting local non-detection as local absences.
Organismal scope terms
An explicitly stated target or excluded organismal scope, and clarification as to whether or not all target organisms observed were reported, should be indicated using the following terms:
life stage: eco:targetLifeStageScope, eco:excludedLifeStageScope, eco:isLifeStageScopeFullyReported
growth form: eco:targetGrowthFormScope, eco:excludedGrowthFormScope, eco:isGrowthFormScopeFullyReported
degree of establishment: eco:targetDegreeOfEstablishmentScope, eco:excludedDegreeOfEstablishmentScope, eco:isDegreeOfEstablishmentScopeFullyReported  
Other organismal scopes should be reported using eco:verbatimTargetScope. 

[[table-10]]
.Organismal scope terms, their recommended usage (status), and example data entries.
|===
|Status |Term |Example entry
.8+|Share if available
|term:eco[targetLifeStageScope]
|`larva`

|term:eco[excludedLifeStageScope]
|`adult`, `juvenile`

|term:eco[isLifeStageScopeFullyReported]
|`TRUE` or `FALSE`

|term:eco[targetDegreeOfEstablishmentScope]
|`native`

|term:eco[excludedDegreeOfEstablishmentScope]
|`invasive`

|term:eco[isDegreeOfEstablishmentScopeFullyReported]
|`TRUE` or `FALSE`

|term:eco[targetGrowthFormScope]
|`tree`

|term:eco[excludedGrowthFormScope]
|`shrub`

|term:eco[isGrowthFormScopeFullyReported]
|`TRUE` or `FALSE`
|===

==== Bycatch

*What is bycatch?*

Bycatch are organisms detected during a survey that were not explicitly targeted in the scope of a study.

+==== Bycatch terms

Bycatch can be reported at the taxonomic and organismal levels. 

If taxonomic bycatch are included in the datasets: 

* Populate term:eco[hasNonTargetTaxa] as `TRUE` at all relevant event levels.
* If ALL taxonomic bycatch (eco:hasNonTargetTaxa = `TRUE`) captured/observed during an Event are reported in the dataset
    * term:eco[areNonTargetTaxaFullyReported] = `TRUE` 
    * and a list of taxonomic bycatch should be provided in eco:nonTargetTaxa. 

If *organismal( bycatch are included in the dataset:

* Then term:eco[hasNonTargetOrganisms] = `TRUE` at all relevant event levels.

If the dataset does NOT include taxonomic or organismal bycatch:

* Populate term:eco[hasNonTargetTaxa] and term:eco[hasNonTargetOrganisms] as `FALSE` at all relevant event levels. 

[[table-11]
.Bycatch terms, their recommended usage (status), and example data entries
|===
|Status |Term |Example entry
.4+|Share if available
|term:eco[hasNonTargetTaxa]
|`TRUE` or `FALSE`

|term:eco[areNonTargetTaxaFullyReported]
|`TRUE` or `FALSE`

|term:eco[nonTargetTaxa]
`Parabuteo unicinctus`, `Geranoaetus melanoleucus; Cetoniinae`, `Aclopinae`, `Cyclocephala modesta`

|term:eco[hasNonTargetOrganisms]
|`TRUE` or `FALSE`
|===

==== Habitat scope

===== Habitat scope terms

An explicitly stated habitat scope should be reported using term:eco[targetHabitatScope] and term:eco[excludedHabitatScope].

[[table-12]]
.Habitat scope terms, their recommended usage (status), and example data entries
|===
|Status |Term | Example entry
.2+|Share if available
|term:eco[targetHabitatScope]
|`deciduous forest`

|term:eco[excludedHabitatScope]
|‘urban’  | ‘grassland’
|===


