=== Scope and completeness

*What are survey scope and survey completeness?*

*Scope* relates to the biodiversity targeted (or not targeted) during a survey. *Completeness* indicates the thoroughness of a survey relative to the stated scope. Structured reporting of explicitly stated survey scopes and completeness is necessary for evaluating and reporting completeness and is critical to understanding if the data can be used to assert absences (non-detections) of taxa.

Scope terms can be applied at any event level and recommended best practice is to report only the information that is explicitly available.

==== Verbatim scope

The full verbatim scope explicitly identifying the full suite of stated parameters defining the breadth of a sampling event should be reported using term:eco[eco:verbatimTargetScope]. term:eco[eco:verbatimTargetScope] is particularly useful for capturing scope conditions not covered by existing taxonomic or organismal scope terms.

[[table-08]]
.General scope terms, their recommended usage (status), and example data entries.
[cols="20,30,~"]
|===
|Status |Term |Example entry
|Recommended
|term:eco[eco:verbatimTargetScope]
|`Adult flying insects`
|===

==== Taxonomic scope

===== Why is taxonomic scope important?

Providing taxonomic scope enables reliable, quantitative, including statistical interpretation of survey and monitoring data. It is essential to interpret local non-detection as local absences.

===== Taxonomic scope terms

An explicitly stated targeted or intentionally excluded taxonomic scope should be reported using term:eco[eco:targetTaxonomicScope] and term:eco[eco:excludedTaxonomicScope].

* If a specific person or persons is recorded as making the taxonomic identifications relevant to the stated survey scope(s), they should be acknowledged using term:dwc[dwc:identifiedBy] (for one or more names) or term:dwc[dwc:identifiedByID] (for one or more unique identifiers such as, OrcID).
* If every organism included in term:eco[eco:targetTaxonomicScope] that was observed during an event was reported, then term:eco[eco:isTaxonomicScopeFullyReported] = `TRUE;` if not, term:eco[eco:isTaxonomicScopeFullyReported] = `FALSE.`

If taxonomic completeness is known, term:eco[eco:taxonCompletenessReported] should be populated as either `reportedComplete` or `reportedIncomplete` and the method used to assess completeness reported in term:eco[eco:taxonCompletenessProtocols]. If taxonomic completeness is not reported, term:eco[eco:taxonCompletenessReported] = `notReported.`

[[table-09]]
.Taxonomic scope terms, their recommended usage (status), and example data entries.
[cols="20,30,~"]
|===
|Status |Term |Example entry
.2+|Recommended
|term:eco[eco:targetTaxonomicScope]
|`Arthropods`

|term:eco[eco:excludedTaxonomicScope]
|`Aves`, `Mammalia`

.5+|Share if available
|term:dwc[dwc:identifiedBy]
|`Cecilie Svenningsen` | `Kevin Holston` 

|term:dwc[dwc:identifiedByID]
|`https://orcid.org/0000-0002-9216-2917` | `https://orcid.org/0000-0002-0786-4069`

|term:eco[eco:isTaxonomicScopeFullyReported]
|`TRUE` or `FALSE`

|term:eco[eco:taxonCompletenessReported]
|`reportedComplete`, `reportedIncomplete`, or `notReported` 

|term:eco[eco:taxonCompletenessProtocols]
|`Based on sampling effort`
|===

==== Organismal scope

===== Why are organismal scope terms important?

As with taxonomic scope, providing organismal scope information when relevant enables reliable, quantitative interpretation of survey and monitoring data and can be essential to interpreting local non-detection as local absences.

===== Organismal scope terms

An explicitly stated target or excluded organismal scope, and clarification as to whether or not all target organisms observed were reported, should be indicated using the following terms:

* *Life stage*: term:eco[eco:targetLifeStageScope], term:eco[eco:excludedLifeStageScope], term:eco[eco:isLifeStageScopeFullyReported]
* *Growth form*: term:eco[eco:targetGrowthFormScope], term:eco[eco:excludedGrowthFormScope], term:eco[eco:isGrowthFormScopeFullyReported]
* *Degree of establishment*: term:eco[eco:targetDegreeOfEstablishmentScope], term:eco[eco:excludedDegreeOfEstablishmentScope], term:eco[eco:isDegreeOfEstablishmentScopeFullyReported]

Other organismal scopes should be reported using term:eco[eco:verbatimTargetScope].

[[table-10]]
.Organismal scope terms, their recommended usage (status), and example data entries.
[cols="20,30,~"]
|===
|Status |Term |Example entry
.8+|Share if available
|term:eco[eco:targetLifeStageScope]
|`larva`

|term:eco[eco:excludedLifeStageScope]
|`adult`, `juvenile`

|term:eco[eco:isLifeStageScopeFullyReported]
|`TRUE` or `FALSE`

|term:eco[eco:targetDegreeOfEstablishmentScope]
|`native`

|term:eco[eco:excludedDegreeOfEstablishmentScope]
|`invasive`

|term:eco[eco:isDegreeOfEstablishmentScopeFullyReported]
|`TRUE` or `FALSE`

|term:eco[eco:targetGrowthFormScope]
|`tree`

|term:eco[eco:excludedGrowthFormScope]
|`shrub`

|term:eco[eco:isGrowthFormScopeFullyReported]
|`TRUE` or `FALSE`
|===

==== Bycatch

===== What is bycatch?

*Bycatch* are organisms detected during a survey that were not explicitly targeted in the scope of the survey.

===== Bycatch terms

Bycatch can be reported at the taxonomic and organismal levels. 

If *_taxonomic_* bycatch information is included in the dataset: 

* Populate term:eco[eco:hasNonTargetTaxa] as `TRUE` at all relevant event levels.
* If ALL taxonomic bycatch (term:eco[eco:asNonTargetTaxa] = `TRUE`) captured/observed during an Event are reported in the dataset, then
** term:eco[eco:areNonTargetTaxaFullyReported] = `TRUE` and
** a list of taxonomic bycatch should be provided in term:eco[eco:nonTargetTaxa].

If *_organismal_* bycatch are included in the dataset, then

* term:eco[eco:hasNonTargetOrganisms] = `TRUE` at all relevant event levels.

If the dataset does NOT include taxonomic or organismal bycatch, then at all relevant event levels

* term:eco[eco:hasNonTargetTaxa] = 'FALSE' and 
* term:eco[eco:hasNonTargetOrganisms] = `FALSE`. 

[[table-11]]
.Bycatch terms, their recommended usage (status), and example data entries
[cols="20,30,~"]
|===
|Status |Term |Example entry
.4+|Share if available
|term:eco[eco:hasNonTargetTaxa]
|`TRUE` or `FALSE`

|term:eco[eco:areNonTargetTaxaFullyReported]
|`TRUE` or `FALSE`

|term:eco[eco:nonTargetTaxa]
|`Parabuteo unicinctus`, `Geranoaetus melanoleucus; Cetoniinae`, `Aclopinae`, `Cyclocephala modesta`

|term:eco[eco:hasNonTargetOrganisms]
|`TRUE` or `FALSE`
|===

==== Habitat scope

===== Habitat scope terms

An explicitly stated habitat scope should be reported using term:eco[eco:targetHabitatScope] and term:eco[eco:excludedHabitatScope].

[[table-12]]
.Habitat scope terms, their recommended usage (status), and example data entries
[cols="20,30,~"]
|===
|Status |Term | Example entry
.2+|Share if available
|term:eco[eco:targetHabitatScope]
|`deciduous forest`

|term:eco[eco:excludedHabitatScope]
|`urban`, `grassland`
|===
