=== Scope and completeness

What are survey scope and survey completeness?

Scope relates to the biodiversity targeted (or not targeted) during a survey. Completeness indicates the thoroughness of a survey relative to the stated scope. Structured reporting of explicitly stated survey scopes and completeness is necessary for evaluating and reporting completeness and is critical to understanding if the data can be used to assert absences (non-detections) of taxa.

Scope terms can be applied at any event level and recommended best practice is to report only the information that is explicitly available.

==== Verbatim scope

The full verbatim scope explicitly identifying the full suite of stated parameters defining the breadth of a sampling event should be reported using eco:verbatimTargetScope. eco:verbatimTargetScope is particularly useful for capturing scope conditions not covered by existing taxonomic or organismal scope terms.

General scope terms, their recommended usage (status), and example data entries.
Status
Term
Example entry
Recommended
eco:verbatimTargetScope
‘Adult flying insects’

==== Taxonomic scope

Why is taxonomic scope important?

Providing taxonomic scope enables reliable, quantitative, incl. statistical interpretation of survey and monitoring data. It is essential to interpret local non-detection as local absences.

Taxonomic scope terms

An explicitly stated targeted or intentionally excluded taxonomic scope should be reported using eco:targetTaxonomicScope and eco:excludedTaxonomicScope. 
If a specific person or persons is recorded as making the taxonomic identifications relevant to the stated survey scope(s), they should be acknowledged via dwc:identifiedBy. Best practice is to use a unique identifier (e.g., OrcID) if available.
If every organism included in eco:targetTaxonomicScope that was observed during an event was reported, then eco:isTaxonomicScopeFullyReported = ‘TRUE’; if not, eco:isTaxonomicScopeFullyReported = ‘FALSE’. 
If taxonomic completeness is known, eco:taxonCompletenessReported should be populated as either ‘reportedComplete’ or ‘reportedIncomplete’ and the method used to assess completeness reported in eco:taxonCompletenessProtocols. If taxonomic completeness is not reported, eco:taxonCompletenessReported = ‘notReported’.

Taxonomic scope terms, their recommended usage (status), and example data entries.
Status
Term
Example entry
Recommended
eco:targetTaxonomicScope
‘Arthropods’
eco:excludedTaxonomicScope
‘Aves | Mammalia’
Share if available
dwc:identifiedBy
‘https://orcid.org/0000-0002-9216-2917’ | ‘https://orcid.org/0000-0002-0786-4069’
eco:isTaxonomicScopeFullyReported
‘TRUE’ or ‘FALSE’
eco:taxonCompletenessReported 
‘reportedComplete’,  ‘reportedIncomplete’, or ‘notReported’ 
eco:taxonCompletenessProtocols
‘Based on sampling effort’

==== Organismal scope
Why are organismal scope terms important?
As with taxonomic scope, providing organismal scope information when relevant enables reliable, quantitative interpretation of survey and monitoring data and can be essential to interpreting local non-detection as local absences.
Organismal scope terms
An explicitly stated target or excluded organismal scope, and clarification as to whether or not all target organisms observed were reported, should be indicated using the following terms:
life stage: eco:targetLifeStageScope, eco:excludedLifeStageScope, eco:isLifeStageScopeFullyReported
growth form: eco:targetGrowthFormScope, eco:excludedGrowthFormScope, eco:isGrowthFormScopeFullyReported
degree of establishment: eco:targetDegreeOfEstablishmentScope, eco:excludedDegreeOfEstablishmentScope, eco:isDegreeOfEstablishmentScopeFullyReported  
Other organismal scopes should be reported using eco:verbatimTargetScope. 

Organismal scope terms, their recommended usage (status), and example data entries.
Status
Term
Example entry
Share if available
eco:targetLifeStageScope
‘larva’
eco:excludedLifeStageScope
‘adult | juvenile’
eco:isLifeStageScopeFullyReported
‘TRUE’ or ‘FALSE’
eco:targetDegreeOfEstablishmentScope
‘native’
eco:excludedDegreeOfEstablishmentScope
‘invasive’
eco:isDegreeOfEstablishmentScopeFullyReported 
‘TRUE’ or ‘FALSE’
eco:targetGrowthFormScope
‘tree’
eco:excludedGrowthFormScope
‘shrub’
eco:isGrowthFormScopeFullyReported
‘TRUE’ or ‘FALSE’



==== Bycatch

What is bycatch?

Bycatch are organisms detected during a survey that were not explicitly targeted in the scope of a study.

===== Bycatch terms

Bycatch can be reported at the taxonomic and organismal levels. 
If taxonomic bycatch are included in the datasets: 
Populate eco:hasNonTargetTaxa as ‘TRUE’ at all relevant event levels. 
If ALL taxonomic bycatch (eco:hasNonTargetTaxa = ‘TRUE’) captured/observed during an Event are reported in the dataset
eco:areNonTargetTaxaFullyReported = ‘TRUE’ 
and a list of taxonomic bycatch should be provided in eco:nonTargetTaxa. 
If organismal bycatch are included in the dataset:
Then eco:hasNonTargetOrganisms = ‘TRUE’ at all relevant event levels. 
If the dataset does NOT include taxonomic or organismal bycatch:
Populate eco:hasNonTargetTaxa and eco:hasNonTargetOrganisms as ‘FALSE’ at all relevant event levels. 

Bycatch  terms, their recommended usage (status), and example data entries.
Status
Term
Example entry
Share if available
eco:hasNonTargetTaxa
‘TRUE’ or ‘FALSE’
eco:areNonTargetTaxaFullyReported
‘TRUE’ or ‘FALSE’
eco:nonTargetTaxa
‘Parabuteo unicinctus | Geranoaetus melanoleucus; Cetoniinae | Aclopinae | Cyclocephala modesta’
eco:hasNonTargetOrganisms
‘TRUE’ or ‘FALSE’

==== Habitat scope

===== Habitat scope terms

An explicitly stated habitat scope should be reported using eco:targetHabitatScope and eco:excludedHabitatScope. 

Habitat scope terms, their recommended usage (status), and example data entries.
Status
Term
Example entry
Share if available
eco:targetHabitatScop
‘deciduous forest’
eco:excludedHabitatScope
‘urban’  | ‘grassland’

