=== Sampling Effort

===== What is sampling effort?

*Sampling effort* communicates sampling intensity during a sampling event. Clear reporting of sampling effort is necessary to interpret measures of completeness and calculate abundance (relative or absolute) or biomass and is critical in assessing the ability to compare information and aggregate data across studies.

===== Sampling effort terms

term:dwc[dwc:samplingEffort] is strongly recommended to publish term:dwc[dwc:Event] datasets to GBIF, however, the Humboldt extension includes five (5) terms to more explicitly capture sampling effort information:

* *Is sampling effort reported?*: term:eco[eco:isSamplingEffortReported] indicates (`true` or `false`) if sampling effort is reported. 
* *Sampling effort*: term:eco[eco:samplingEffortValue] and term:eco[eco:samplingEffortUnit] report sampling effort value and units (e.g. 4 trap nights).
* *Sampling effort protocol*: term:eco[eco:samplingEffortProtocol] should contain a textual description of the sampling effort protocol (e.g. number and arrangement of people or sensors deployed, whether or not sensors were mobile or stationary, how frequently observation, measurements, or samples were taken) and/or provide a link to the protocol used.
* *Sampling performed by*: term:eco[eco:samplingPerformedBy] should be used to credit the people involved in the sampling eventSampling effort terms, their recommendation usage, and example data entries. Best practice is to use a unique identifier (e.g., OrcID) if available.
** NOTE: Because term:eco[eco:samplingPerformedBy] has an IRI equivalent only a single OrcID can be provided (the term cannot support a list). If more than one OrcID needs to be shared, a list of OrcID’s (using the pipe separator between values) can be supplied using the term term:dwc[dwc:recordedByID] used BUT it must be applied to each relevant occurrence and located on the `occurrence` table. 

****

[discrete]
===== Updated recommended best practice 

Capture sampling effort information as structured data using the five (5) Humboldt extension terms:

* term:eco[eco:isSamplingEffortReported]
* term:eco[eco:samplingEffortValue] and term:eco[samplingEffortUnit]
* term:eco[eco:samplingEffortProtocol] 
* term:eco[eco:samplingPerformedBy]
****

[[table-13]]
.Sampling effort terms, their recommended usage (status), and example data entries
[cols="20,30,~"]
|===
|Status |Term |Example entry
.6+|Recommended
|term:eco[eco:isSamplingEffortReported]
|`true` or `false`

|term:eco[eco:samplingEffortProtocol]
|`40 box traps deployed in the afternoon even spacings along 4 parallel 100m transects placed 50m apart and visited after sunrise the next day`

|term:eco[eco:samplingEffortValue]
|`40`

|term:eco[eco:samplingEffortUnit]
|`trap nights`

|term:dwc[eco:samplingEffort]
|`40 trap nights`

|term:eco[eco:samplingPerformedBy]
|`‘A. Townsend Peterson`, 'https://orcid.org/0000-0003-0243-2379'
|===
