[appendix]

== Additional DwC Event terms

While all https://eco.tdwg.org/[Humboldt extension] terms are covered in this guide, the Darwin Core Event terms included are not exhaustive. The full suite of available DwC Event terms that can be applied to a DwC-A Event dataset can be found in the https://rs.gbif.org/core/dwc_event_2024-02-19.xml[GBIF Repository of Schemas Darwin Core Event page].

== Additional guidance and seeking assistance

Need more information? Check out the following documentation: 

* https://eco.tdwg.org/[Humboldt Extension for Ecological Inventories^] 
* https://techdocs.gbif.org/en/[GBIF Technical Documents^] 

Or, reach out for assistance from:

* https://discourse.gbif.org[Humboldt Extension GitHub repository^]: questions about usage, issues with the vocabulary, and recommendations for new terms should be reported as an Issue.
* https://discourse.gbif.org[GBIF community forum on Discourse^]
* GBIF help desk 
    ** https://techdocs.gbif.org/en/[create an issue on the GitHub tech-docs project^] 
    ** mailto:helpdesk@gbif.org[send an email^] 
