== Summary

The details about a biological survey (how it was carried out, the spatio-temporal scope, the taxonomic groups targeted, who was involved, etc.) are important to properly understand the structure of the survey and how the published data can be reused. The https://eco.tdwg.org/[Humboldt Extension for Ecological Inventories^] (HE), a vocabulary extension to the https://dwc.tdwg.org/[Darwin Core^] (DwC) Event https://www.gbif.org/dataset-classes[Class^], provides a means by which to explicitly report the context in which species occurrence data and/or material specimens were collected. The extension includes 55 terms to capture critical facets of survey design including protocol, scope, and sampling effort in a structured manner, thus enhancing overall FAIRness (specifically findability and interoperability) of biological survey data. 

This document will guide GBIF data publishers who (a) already have data formatted as a Darwin Core (DwC) Event dataset through the process of updating their dataset with the https://eco.tdwg.org/[Humboldt extension^] or (b) are comfortable with the DwC Event core and wish to map a new dataset as a DwC Event class to DwC https://rs.gbif.org/core/dwc_event_2024-02-19.xml[Event class^] and https://eco.tdwg.org/[Humboldt extension^] terms. 

If you are not yet comfortable with Darwin Core Event dataset and are looking for more in-depth guideance in structuring a your data following Darwin Core guidelines, refere to the more comprehensive document, https://doi.org/10.35035/doc-ynvs-eh84[+++Guide for publishing biological survey and monitoring data to GBIF+++].
