== Summary

The details about a biological survey (how it was carried out, the spatio-temporal scope, the taxonomic groups targeted, who was involved, etc.) are important to properly understand the structure of the survey and how the published data can be reused. The https://eco.tdwg.org/[Humboldt Extension for Ecological Inventories^] (HE), a vocabulary extension to the https://dwc.tdwg.org/[Darwin Core^] (DwC) Event https://www.gbif.org/dataset-classes[Class^], provides a means by which to explicitly report the context in which species occurrence data and/or material specimens were collected. The extension includes 55 terms to capture critical facets of survey design including protocol, scope, and sampling effort in a structured manner enhancing overall FAIRness (specifically findability and interoperability) of biological survey data. 

This document will guide GBIF data publishers who already have data formatted as a Darwin Core (DwC) Event dataset through the process of updating their dataset with the https://eco.tdwg.org/[Humboldt extension^]. 
